extends:
    [
        'stylelint-config-standard-scss',
        'stylelint-config-prettier',
        'stylelint-prettier/recommended',
    ]
plugins:
  [
    'stylelint-scss'
  ]
rules: [
   ]
overrides: [{ files: ["**/*.scss"], customSyntax: "postcss-scss" }]
