extends:
    [
        'stylelint-config-standard-scss',
        'stylelint-config-prettier',
        'stylelint-prettier/recommended',
    ]
plugins:
  [
    'stylelint-scss'
  ]
rules:
    'scss/at-rule-no-unknown': null
    'scss/dollar-variable-pattern': '^foo'
    'scss/selector-no-redundant-nesting-selector': true

overrides: [{ files: ["**/*.scss"], customSyntax: "postcss-scss" }]
